### ISSUE TITLE
I'm sorry but could you please tell us how to use the code.Thanks.

### ISSUE THREAD

**Issue by xu-cpp** [isidorjkaplan/Metsco_Insulator_Detection#1]
I'm sorry but could you please tell us how to use the code.Thanks.

**Comment by isidorjkaplan** [comment]
Hey! Sorry for the late reply, I only just saw this. The code itself is a bit of a mess. I mainly was using it as a proof of concept for a school project and we never submitted the code, only the results. 

The truth is I do not really remember exactly how to run it since this was a while ago. Since writing this my more recent projects I have been much better about documenting properly as a lesson learned from this project. 

From what I recall, the final_design/data_reader.py file parses the data, which was generated by labelbox and exported into the data.json file, and it downloads them into a format that can be used for the machine learning. It basically separates the files into folders of "masks" and "images" where the image is in one and the mask for the corresponding image is in the other. The original masks were manually labelled using labelbox and used as training data. 

After that the program "final_design/netwok.py" is what actually trains the network. When you run it this file uses the format from data_reader.py and trains a network to generate the maps. 

After that the program "final_design/program.py" runs the program on a set of images that is specific somewhere in the code and it generates the heat maps, crops them, and prints the results. This is used for validation/testing
